# Generated by Django 5.1.2 on 2024-12-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
